// OpenAPI Service System Exports
export { OpenApiTypeGenerator } from './OpenApiTypeGenerator';
export { OpenApiClient } from './OpenApiClient';
export { ServiceGenerator, BaseApiService } from './ServiceGenerator';
export { OpenApiServiceFactory } from './OpenApiServiceFactory';
export { AutoGeneratedComplaintsService } from './AutoGeneratedComplaintsService';

// Types
export type { OperationInfo } from './OpenApiTypeGenerator';
export type { RequestOptions, ApiResponse } from './OpenApiClient';

// Helper function to quickly create an OpenAPI-based service
export async function createOpenApiService<T = any>(
  tag: string, 
  baseUrl: string = process.env.VITE_API_URL || 'http://localhost/api',
  specPath: string = '/api/openapi.yaml'
): Promise<T> {
  const { OpenApiServiceFactory } = await import('./OpenApiServiceFactory');
  const factory = new OpenApiServiceFactory(baseUrl);
  await factory.initialize(specPath);
  return factory.getService<T>(tag);
}

// Utility to check if OpenAPI services are available
export function isOpenApiEnabled(): boolean {
  return process.env.VITE_USE_OPENAPI === 'true' && process.env.NODE_ENV !== 'development';
}